menu:
  docs:
    - name: Intro
      title: Intro to Simple CMS
    - name: Accounts
      title: Account Settings
    - name: Configuration
      title: Configuring your Site
    - name: Media
      title: Media
    - name: Workflow
      title: Workflow
    - name: Collections
      title: Collections
    - name: Fields
      title: Fields
    - name: Guides
      title: Platform Guides
    - name: Customization
      title: Customizing Simple CMS
    - name: Contributing
      title: Community
