name: Website

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - website/**
  pull_request:
    branches: [ "main" ]
    paths:
      - website/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: yarn
        cache-dependency-path: website/yarn.lock
        node-version: 16
        
    - name: Install
      working-directory: ./website
      run: |
        yarn install --frozen-lockfile
        
    - name: Lint
      working-directory: ./website
      run: |
        yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
